### ISSUE TITLE
[documentation] Add aggregation metircs description

### ISSUE THREAD

**Issue by Bukharovsi** [ru-fix/aggregating-profiler#34]
Could you please add metrics description to Readme files. 

There are no a clear difference between `callsThroughputAvg  ` and `throughputPerSecondMax`. Also, tests do not describe it.
Could you please provide some example and show us the difference

**Comment by swarmshine** [comment]
Could you please check out new version of docs with pictures in readme. 
https://github.com/ru-fix/aggregating-profiler
