### ISSUE TITLE
Need to add explanation how to build the profiler

### ISSUE THREAD

**Issue by Bukharovsi** [ru-fix/aggregating-profiler#8]
Kamil, Could you add to `readme` information how to build the profiler. It is the very important thing for contributing.

**Comment by swarmshine** [comment]
Could you please clarify what you mean when you say 'build the profiler': 
how to build project aggregating profiler   
or how to prepare AggregatingProfiler class and how to regularly build reports with it ?

**Comment by swarmshine** [comment]
added docs
